sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QsPexZJ3uVgsRPOEOIwSgYk8O2Lckx7eCo+jyTWhRmVktPPwO8aF/HSPkwSyfp5HLwd8cNjMLfXjN+ueBKxIDXiTMcgorxDyBJ/oW6JkTdfEDBX+KoIlgYGPgeYNdJyPeQ/PfnRFwBC/R6pAMSC4kxt9P0B9g4aJZ4zj3otQgR5PXX0M3Poo9FhdYOVViOWD13GSnNPDCdYOpvdWOLJttsE6ev8ApkQ19aVlaMrBDLlR1OhaFQApYXn6kcuQoQ4EcTuREK5mZ+jKcFvewl+fUHQwFLTdYQrV3pmavzvKzzy2RFAovEiIjM0ZXNrkcDS1cRREaqloJpm8OE/cDeKYJqoHHOc0Ofq5ySgcUrknvVs84cp4Czb9yzk0mlRCd9wqQNJYqecuyXRseu0MZ+bu4f7wGhbXACkVku6RLnv3u7v6NkhdKu5zSWvSmG9DxoqwKbNOVkejcG88ufxRVU1k07feGW5Aok5oLc5N6aYSnzTZPKcGlN7/bFUM/zyQwc4kybN5L7rZ4hWSbJ+FhO2ZpbfHxkhbcDhXa16HtAyED+jSh2/DjO+sWuqLazIU/3SBAS4HVJgQFH/50zIONQBd+OWaPMWXov7OuLwCjYl3GUCq6nL+7kqKMAzuuW587qTpfrY1nmzLuoK5jflrcSqFxYBgu3AuklwU1/iFiMsobr8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Recollections-and-Letters-of-General-Robert-E.-Lee_2323
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy